### ISSUE TITLE
Problem quiting all apps while in CoverflowAltTab.

### ISSUE THREAD

**Issue by mcoyle1960** [dmo60/CoverflowAltTab#102]
With CoverflowAltTab active, quitting all apps does not exit the extension. In fact, there is no way to exit and you're stuck with an empty CoverflowAltTab screen. The only workaround I've found is relaunch the DE. (Gnome 3.32.1)

Thanks for all the work.

**Comment by p91paul** [comment]
I've tried to reproduce but I failed.
I opened a few windows, triggered alt-tab, then closed everything with 'q'. The animation just went away leaving me to the desktop as I expected.

Can you provide exactly how you trigger this error? Please also collect logs from journalctl.

**Comment by mcoyle1960** [comment]
I'm sorry, It's no longer doing it. I'll keep an eye on the situation and if I can reliably reproduce it, I'll come back and update you.  Love the extension. Thanks for the hard work.

**Comment by p91paul** [comment]
No problem, let's hope it doesn't happen again!
