### ISSUE TITLE
I want to use switch system controls key

### ISSUE THREAD

**Issue by aerfanr** [dmo60/CoverflowAltTab#104]
Is there any way to tell coverflow alt-tab to don't use this keybinding? I need it. Some times there is no mouse.

**Comment by p91paul** [comment]
Which keybinding is this? "system controls" doesn't ring a bell, sorry.

You can try tinkering with the file keybinder.js, from line 61; just comment out (adding // in front of it) the various "Main.wm.setCustomKeybindingHandler", one at a time, until you find the one you want. After each modification you need reload gnome-shell for it to make effect.
