### ISSUE TITLE
After using Alt+Tab combination, maximized windows on the secondary monitor don't fit vertically the entire screen

### ISSUE THREAD

**Issue by JayBeeDe** [dmo60/CoverflowAltTab#109]
Hi,
I have an issue on CentOS 7 with gnome 3 and the following configuration:
- ConverflowAltTab extension is enabled
- extended desktop with 2 monitors
- 2 identical monitors (2x 1920x1080pixels, monitors are horizontally aligned => 3840x1080 pixels)
- **top bar and window bar only on the primary monitor (left monitor)**
- Coverflow alt-tab activated and configured as follow :
![Screenshot from 2019-09-25 16-24-06](https://user-images.githubusercontent.com/17429937/65610252-5df42e80-dfb1-11e9-9d48-9a432bf07e4a.png)

Here are the reproduction steps:
- a window is maximized on the secondary monitor
- switch to another window with alt+tab (which is already on the primary monitor) :
=> It switches to the window on the primary monitor, but, until a desktop refresh occurs (seems to be around 2 minutes), any window on the secondary monitor cannot be really maximized : its size is as if there were a top bar and a window bar on the secondary monitor (which is not the case) :
![Screenshot from 2019-09-25 16-26-04](https://user-images.githubusercontent.com/17429937/65610659-f1c5fa80-dfb1-11e9-8293-d71c6bfd9f17.png)

After 1 or 2 minutes the window finally fits the entire screen. It is also possible to manually trigger this refresh by going and leaving the _Activities Overview_.

**Comment by p91paul** [comment]
I never was able to reproduce this. When you get the latest update (gs 3.36+ only) please let me know if this is still an issue for you.
