### ISSUE TITLE
Window Title Box font does not scale on HIDPI screens

### ISSUE THREAD

**Issue by SubhamSatyajeet** [dmo60/CoverflowAltTab#111]
Ubuntu 19.04
Gnome Shell 3.32.2

Currently, the window title box's font size is set according to the resolution of the screen. If you change the scaling factor (via Gnome Tweaks), the font size does not change. This results in tiny fonts on a 1080p 15" laptop screen/other HIDPI displays.

There are 2 possible approaches:
1) Make the font size in the application titlebar scale according to the scaling factor being used
2) Allow hiding the application titlebar and the application icon, via extension setting (A setting "Off" could be added alongside "Bottom" and "Top" for Window Title Box Position within extension settings.)

**Comment by dsheeler** [comment]
@SubhamSatyajeet I'm working on this and might commit very soon. 

https://user-images.githubusercontent.com/1632985/178368555-0616a119-b5fa-4e10-b10d-b15439b9a5bf.mp4
