### ISSUE TITLE
Mouse issues

### ISSUE THREAD

**Issue by doktorjw** [dmo60/CoverflowAltTab#115]
I'm running Ubuntu 19.10, with a 4k main display and a 2k secondary display. The main display is a big Vizio 4k lcd tv, actually, while the secondary is a Dell 2k in portrait mode.

With coverflowAltTab installed, I periodically get mouse inputs blocked. It sounds like many issues I've found that have been reported over the years, but .... this only happens with this one extension installed. I uninstalled all extensions ... and I run fine. I install only coverflow and ... an hour or so later, my mouse input is disabled. It appear to happen when transitioning the mouse from the 4k to the 2k --- mouse clicks stop working on the secondary display. Switching back to the main display, only the window in front receives mouse clicks. Sometimes it stays like that, sometimes all mouse click ability goes away.

I love the look of Coverflow ... but unfortunately, I can't deal with 1/2 dozen times a day having to restart my gnome session to free up mouse input (and sometimes I can't do that because it seems the keyboard stops responding).

**Comment by p91paul** [comment]
can you get logs from journalctl when the freeze happens?

**Comment by doktorjw** [comment]
Sorry I haven't responded. I'll try to recreate it this afternoon & remote log into the box and get the logs.

**Comment by doktorjw** [comment]
Here you go; hopefully I left enough in the log that you can investigate. Had the issue this morning.

[journalctl.gz](https://github.com/dmo60/CoverflowAltTab/files/4140063/journalctl.gz)

**Comment by p91paul** [comment]
I got in a bad loop at work and I'm not out yet. I cannot tell when I'll look into this issue. I'm very sorry.

**Comment by doktorjw** [comment]
Not a problem. I've been in work-hell the last several weeks as well, trying to track down some pretty strange issues. It happens. :)

**Comment by doktorjw** [comment]
As an FYI; I've updated to Ubuntu 20.04 .... and re-enabled coverflow alt-tab and I've not had any issues in the last couple of days. With 19.10, it would cause me grief with minutes, generally, or maybe after 1/2 hour to an hour. Lately ... nothing.

One other difference is that I'm not running one monitor in portrait mode --- it's a separate issue there, not related to this plugin, where Gnome/nvidia isn't saving the configuration of my displays, causing me to run my displays this way, or to manually set up the displays after every reboot.

**Comment by p91paul** [comment]
Seeing that with a system upgrade it got better, I'm going to close this issue.
Sorry I wasn't really helpful, if it happens again please reopen with fresh logs.
