### ISSUE TITLE
Multi-monitor issues on 3.36

### ISSUE THREAD

**Issue by p91paul** [dmo60/CoverflowAltTab#122]
See https://github.com/dmo60/CoverflowAltTab/issues/117

**Comment by rockorequin** [comment]
I think this might have been fixed by an upgrade in gnome-shell/mutter. I'm running gnome-shell 3.36.1-4ubuntu1 and coverflow is working nicely under X11 with two monitors.

**Comment by p91paul** [comment]
Nice, didn't notice your last comment on the other issue. I'll leave this open for a while longer, if noone reports issues I will close it. Thanks!
