### ISSUE TITLE
Doesn't run in gnome-shell 3.37

### ISSUE THREAD

**Issue by rockorequin** [dmo60/CoverflowAltTab#131]
The error message is "No JS module 'tweener' found in search path".

I'm using gnome-shell 3.37.91-1ubuntu1.

**Comment by alex4401** [comment]
Although I switched from this extension to a handmade one, I might submit a PR with these changes if it doesn't look too messy.

**Comment by p91paul** [comment]
That would be nice!

**Comment by alex4401** [comment]
First set of 3 commits is in #132, waiting to be tested, which I can't do myself for next 5 hours.
