### ISSUE TITLE
Create a new develop branch

### ISSUE THREAD

**Issue by machitgarha** [dmo60/CoverflowAltTab#134]
Having a separated `develop` is good. Afterwards, all PRs should be merged into this branch (instead of `master`), and thus, `master` will become more stable. The development process and merging PRs would happen faster, and we could also create release cycles. There are other small benefits, as well as there is almost no downside on creating such a branch.

**Comment by machitgarha** [comment]
There is already an `experimental` branch, however, it is too old. I suggest to remove it and replace it with the new proposed branch, as well as removing all ancient branches, including `gnome-shell-3.2`, `no-option` and `workspaces`. Even if they contain unmerged changes, they are probably old, and we could ignore them.

**Comment by p91paul** [comment]
@machitgarha could you be interested in fixing https://github.com/dmo60/CoverflowAltTab/issues/95 as well? Starting with commit rights on this repo?

**Comment by machitgarha** [comment]
@p91paul Sorry, but no, I can't focus for being a maintainer of this project now. Yes, I would contribute to this project, but as a contributor, not as a maintainer. By the way, I hope it get fixed soon.

**Comment by p91paul** [comment]
Here's what I did: merged both #132 and #133 in the gnome3.37 branch. Works fine on 3.36, going to test it on 3.37 now.

**Comment by alex4401** [comment]
Works for me in a VM with 3.37.91.

**Comment by machitgarha** [comment]
Good. Saw it.

For the `master`-`develop`-other branch model, I've found [this](https://nvie.com/posts/a-successful-git-branching-model/) pretty useful.

**Comment by machitgarha** [comment]
@alex4401 That's great!

**Comment by p91paul** [comment]
me too. This is going to master and e.g.o. Thanks to both of you!

> @p91paul Good. Saw it.
> 
> For the `master`-`develop`-other branch model, I've found [this](https://nvie.com/posts/a-successful-git-branching-model/) pretty useful.

Yeah that's THE git branching model. However, this extension is in maintenance mode, so master + a single purpose branch here and there is more than enough. I did clean obsolete branches though.

**Comment by machitgarha** [comment]
@p91paul Thanks for deleting obsolete branches. However, about the model, it's your choice.
