### ISSUE TITLE
New update does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by Farhaduneci** [dmo60/CoverflowAltTab#136]
Would you fix the issue please, I'm not sure why it's happening

**Comment by p91paul** [comment]
can you post some logs (from journalctl) from the time the issue happens? also what are the symptoms? alt tab does nothing, the animation is missing, or standard alt-tab kicks in?

**Comment by giacar** [comment]
> can you post some logs (from journalctl) from the time the issue happens? also what are the symptoms? alt tab does nothing, the animation is missing, or standard alt-tab kicks in?

No issue for me, just reboot the session after the update, as the gnome console says.

**Comment by Farhaduneci** [comment]
> can you post some logs (from journalctl) from the time the issue happens? also, what are the symptoms? alt-tab does nothing, the animation is missing, or standard alt-tab kicks in?
> 
> No issue for me, just reboot the session after the update, as the gnome console says.

Thanks for that, I restarted the session and evrything were working :dizzy_face:

> can you post some logs (from journalctl) from the time the issue happens? also what are the symptoms? alt tab does nothing, the animation is missing, or standard alt-tab kicks in?

I did not found any log related to that, the problem accured when I tried to update the extention via extentions tab, It just displayed Error, Is there any thing that I can help you with toward this? Do you know were exactly should I look for errors?

**Comment by p91paul** [comment]
Ok if the restart fixes the issue, I guess it's fine!
