### ISSUE TITLE
gnome 3.38 keep wrnning this

### ISSUE THREAD

**Issue by guoqiyi** [dmo60/CoverflowAltTab#138]
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported
Oct 21 00:12:12 nvme gnome-shell[564]: Timelines with detached actors are not supported

**Comment by p91paul** [comment]
you sure this is related to this extension? does it happen only when it is enabled?

**Comment by guoqiyi** [comment]
> you sure this is related to this extension? does it happen only when it is enabled?

Yes,I disabled all other extensions,and running journalctl -f to monitor,when I press Alt+Tab to switch windows,the journalctl log keeps warning this,after half years,this problem still there

**Comment by Zappo-II** [comment]
can confirm, same here...
```
Feb 24 23:03:13 un-tuxedo gnome-shell[1826]: Timelines with detached actors are not supported
Feb 24 23:03:13 un-tuxedo gnome-shell[1826]: Timelines with detached actors are not supported
```
...45 lines deleted...
```
Feb 24 23:03:13 un-tuxedo gnome-shell[1826]: Timelines with detached actors are not supported
Feb 24 23:03:13 un-tuxedo gnome-shell[1826]: Timelines with detached actors are not supported
Feb 24 23:03:13 un-tuxedo gnome-shell[1826]: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
Feb 24 23:03:13 un-tuxedo gnome-shell[1826]: Attempting to remove actor of type 'StWidget' from group of class 'Gjs_ui_layout_UiActor', but the container is not the actor's parent.
```
```
  "url": "https://github.com/dmo60/CoverflowAltTab",
  "uuid": "CoverflowAltTab@palatis.blogspot.com",
  "version": 44
```
and
```
~ >>> gnome-shell --version                                                                                                                                                                                   
GNOME Shell 3.38.3
```

**Comment by p91paul** [comment]
I reproduced this on Gnome 40 as well. Since I have no clue about how to understand what or if I'm doing something wrong, I reported it upstream (https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4098)

**Comment by GeorgesStavracas** [comment]
This error signals that you're adding a timeline (either through `actor.ease()`, or `actor.add_transition()`) to an actor before adding the actor to a parent.
