### ISSUE TITLE
[Feature Request] Add a tray icon to switch via mouse

### ISSUE THREAD

**Issue by mystiquewolf** [dmo60/CoverflowAltTab#140]
I know we have "Activities", but Coverflow is much easier when you have many apps. Please either make Coverflow activate when "Activities" is triggered, or add a new tray icon that triggers Coverflow. Thank you for this great extension.

**Comment by p91paul** [comment]
After thinking about it, I don't think it's the place for this extension to do that.
Ideally, another, separate extension could add a tray icon or hijack the activities overview to launch the 'switch-windows' event or something else.
Also, I'd argue the activities overview is much easier to navigate with many windows, coverflow works for 3 windows, some more in timeline mode, but that's it.
