### ISSUE TITLE
No JS module 'tweener' found in search path

### ISSUE THREAD

**Issue by wildcard-f8** [dmo60/CoverflowAltTab#141]
Linux 5.9.3-1-MANJARO x86_64 20.2
gnome-shell 3.38.1

can't turn on the extension.

**Comment by p91paul** [comment]
you sure you are running the latest version? try updating or reinstalling, this extension was indeed ported to 3.38

**Comment by p91paul** [comment]
Closing for lack of feedback, probably OP was running an outdated version.
