### ISSUE TITLE
gnome 40

### ISSUE THREAD

**Issue by rudrab** [dmo60/CoverflowAltTab#143]
Hello,
any plan for releasing gnome 40 version?

**Comment by p91paul** [comment]
I didn't test on gnome 40 yet.
If it's broken, can you post a log of the error?

**Comment by rudrab** [comment]
No its not broken. thats why I havn't put any error or problem. If you just add "40" in metadata, then its working fine (I build from the git).

**Comment by p91paul** [comment]
good to know, thank you. Will try and issue a new release.
Did you try editing preferences?
Probably some modifications will be needed there...

**Comment by rudrab** [comment]
Hi, 
I had not tried editing preferences, but as with all the pre-40 plugins, this has the same problem:
```
Error: No property border_width on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  buildPrefsWidget@/home/rudra/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/prefs.js:57:14
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by rudrab** [comment]
Dear @p91paul 
I have checked the extension from master branch (somehow git clone doesnt work; I downloaded the zip.). This is to report that it is working fine, without any problem, including the settings.
Thanks a lot.

**Comment by p91paul** [comment]
you have to thank @hiaselhans actually!
Will leave this open until I upload to e.g.o.

**Comment by rudrab** [comment]
> you have to thank @hiaselhans actually!
I have upvoted @hiaselhans's thread. But yes, you guys has made my laptop looking beautiful again.

**Comment by p91paul** [comment]
upload made, waiting for approval!
