### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by MuhammedTaha02** [dmo60/CoverflowAltTab#152]
Hello there. This plugin is very nice. Thanks for the plugin. I have a suggestion and a problem.

My suggestion: It would be perfect if you can do an infinite window loop from the left and right with the Coverflow effect. For example, have A and B windows open. When we Alt + Tab, it will appear as A - B - A or B - A - B

Problem: I am using the dash to dock plugin ewlsh developed for gnome40. Sometimes when I do alt + tab dash to dock appears. Sometimes invisible

Thanks again for the plugin ^^.

**Comment by p91paul** [comment]
Hi, those were already reported as https://github.com/dmo60/CoverflowAltTab/issues/23 and https://github.com/dmo60/CoverflowAltTab/issues/65.
The "Dash to Dock" issue however was resolved many years ago... is it a new Dash to Dock plugin? could you report it to them?

**Comment by MuhammedTaha02** [comment]
As an animation, I guess it would be much better if it was like the link I found there. (Sorry. My english is bad :/  )
https://codepen.io/shshaw/pen/NxWgxJ?editors=001

For Dash to dock, you can follow the commit here.
https://github.com/micheleg/dash-to-dock/pull/1402

Thanks.

**Comment by p91paul** [comment]
Ok then I suggest you let them complete their work on that. Open a new bug on that repository if the issue persists after they merged Gnome 40 support and tag me so I can be of help.
I'm going to close this issue for now.

**Comment by MuhammedTaha02** [comment]
> Ok then I suggest you let them complete their work on that. Open a new bug on that repository if the issue persists after they merged Gnome 40 support and tag me so I can be of help.
> I'm going to close this issue for now.

Thank you for your interest. Goodbye :).
