### ISSUE TITLE
Separate the coverflow on each display

### ISSUE THREAD

**Issue by redgryphon** [dmo60/CoverflowAltTab#153]
Right now when there are multiple displays the coverflow is shown in the one where the focused windows is but it contains all the windows present in the workspace (in all the multiple displays available if the workspace spans the displays).

There should be a chance to configure the extension and allow the user to decide if showing only the windows present in the current display (with current I mean the one that contains the focused window) or keep the current behavior with all the windows.

Another option could also be the one of using the position of the cursor instead of the focused window to decide which display use for the coverflow.

**Comment by p91paul** [comment]
should be implemented in current master. Could you try from manual installation? I will upload to e.g.o., I didn't before to avoid overcharging reviewers shortly after gnome 40 release.
Note: current master supports gnome 40 only and I don't plan on backporting features.

**Comment by redgryphon** [comment]
I confirm it's working on master. I found PR #146 implementing it for reference if needed by other people in the meantime it will be uploaded on extensions.gnome.org.

**Comment by p91paul** [comment]
Version uploaded to e.g.o., it's now pending review.
