### ISSUE TITLE
GNOME 41 compatibility

### ISSUE THREAD

**Issue by myousefnezhad** [dmo60/CoverflowAltTab#162]
Thank you very much for this wonderful extension.

I want to ask you to add GNOME 41 compatibility to your extension.

**Comment by p91paul** [comment]
Did you manage to test if it already works just by adding 41 to `shell-version` in `metadata.json`? I don't have Gnome 41 yet.

**Comment by myousefnezhad** [comment]
Hi again. I indeed changed the "metadata.json" last night. I confirm that the default settings (with modified shell-version) work fine in Fedora 35 (preview) with GNOME 41.0. That's great. Thanks for the excellent extension.

**Comment by fabianhjr** [comment]
Just tried it on NixOS unstable/development branch and it works great on GNOME 41.

There seems to be some flickering but inclined to think it is a GNOME shell issue.

**Comment by p91paul** [comment]
I just uploaded a new version changing just metadata.json.
I hope it will be approved soon; unfortunately, gnome 41 is not on arch linux yet, so I was unable to test it.

**Comment by machitgarha** [comment]
@p91paul

(As a side-note)

Wow, what a great news. I expected Gnome to break something, but that's not the case. So maybe things have changed. If it's a fact, I will be happy. And if it's a long-term decision, then I should "Hey Gnome developers, special thanks for this, and a big thumbs-up". I wish it be true.
