### ISSUE TITLE
Unable to install Coverflow after last update

### ISSUE THREAD

**Issue by dsancheznet** [dmo60/CoverflowAltTab#167]
Since the last update on May 15th 2022 I am unable to install the plugin on Fedora 36. I came from a working version of the plugin and updated it this morning and Firefox throws an error.

I tried deleting and reinstalling and it keeps throwing an error.

Best regards
D.Sánchez

**Comment by dsancheznet** [comment]
After a few reboots it started working again.

Thanks for the extension, great job!

**Comment by dsheeler** [comment]
Sorry about the inconvenience! I'm not sure why that's happening, tbh.  Will try to figure it out!

**Comment by dsheeler** [comment]
@dsancheznet Just found out that error happens with upgrading every extension: the browser shows an error until you restart gnome-shell and reload the page, i.e., NOT MY FAULT :D
