### ISSUE TITLE
Issue with f4 in ubuntu 22.04

### ISSUE THREAD

**Issue by N7K5** [dmo60/CoverflowAltTab#168]
Found a BUG in Ubuntu 22.04 Gnome 42.1 updated from Ubuntu 20.04 =>
while in coverflow, pressing f4 button closes two window in the animation while actually one window is closed (that is, two window gets invisible from coverflow)
playing with the code, found out that, In switcher.js, removing line no 300-
`this._checkDestroyedTimeoutId = Mainloop.timeout_add(
                    CHECK_DESTROYED_TIMEOUT,
                    () => this._checkDestroyed(this._windows[this._currentIndex])
                );`
fixes the problem!!!
![Screenshot from 2022-05-26 16-55-31](https://user-images.githubusercontent.com/19864014/170479836-08653fb9-19f9-4a62-9047-7539d74c0674.png)

**Comment by dsheeler** [comment]
Thanks for reporting! That's a bit of the code I don't understand, atm, but I'll look into it
