### ISSUE TITLE
Selected window disappears, desktop shown

### ISSUE THREAD

**Issue by Tronic** [dmo60/CoverflowAltTab#17]
The switcher itself works fine but every now and then, quite possibly when Alt+Tabbing repeatedly in succession, windows no longer get rendered until when Gnome Shell is restarted. Other than being invisible and desktop background being shown instead, they function normally. I am not entirely sure if this is related to the extension or not but I've seen the problem multiple times since installing the extension. I am now trying with it disabled.

**Comment by p91paul** [comment]
I'm not using gnome at work now, and my usage at home is not so intensive to trigger this bug. Is anybody still seeing it?

**Comment by p91paul** [comment]
A lot of time has passed and I cannot reproduce now. So I'm going to close this issue.
