### ISSUE TITLE
[REQUEST] Carousel style

### ISSUE THREAD

**Issue by firinael** [dmo60/CoverflowAltTab#174]
Hi, I find the default tab switching style kind of jarring when going from last to first. Would it be possible to add a carousel option where the tabs don't really "end"?

Thank you for your work!

**Comment by horshack-dpreview** [comment]
Agree with @firinael. It's the only quibble I have for this excellent extension.

**Comment by EmilyisWIP** [comment]
Any chance this might get added?

**Comment by dsheeler** [comment]
I'll start working on this next, I think!

**Comment by dsheeler** [comment]
I implemented carousel in 8d5e77e65b1999853650ce5dea240de99ed1173b. Yay!
