### ISSUE TITLE
Incompatible with Gnome 43

### ISSUE THREAD

**Issue by tybor** [dmo60/CoverflowAltTab#175]
On https://extensions.gnome.org/extension/97/coverflow-alt-tab/ the extension is currently marked as outdated.

**Comment by dsheeler** [comment]
@tybor, I actually don't see that it says it's outdated.  Can you post a screenshot?

**Comment by tybor** [comment]
![image](https://user-images.githubusercontent.com/97251/193651775-1fb1aa02-4559-4863-b7c1-18fc763539ba.png)

**Comment by tybor** [comment]
Btw, many kudos as it is a really good extension!

**Comment by tybor** [comment]
![image](https://user-images.githubusercontent.com/97251/193690197-61736081-c2b4-49b9-929f-c6203c4851b5.png)

I followed the above suggestion, setting disable-extension-version-validation in org.gnome.shell dconf and it seems to work fine, so AFAICS there's just a "43" missing in metadata.json

**Comment by dsheeler** [comment]
Another way to enable it without setting that dconf setting is to edit the metadata.json file and add "43" to shell-version: 

```
    "shell-version": [
        "42", "43"
    ],
```

**Comment by dsheeler** [comment]
metadata.json would be in `~/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de` if you installed for just your user accout, or `/usr/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de` if you installed for all users.  Probably you installed for just your user account.
