### ISSUE TITLE
Coverflow for alt+tab only (not for super-tab)

### ISSUE THREAD

**Issue by kirmaha** [dmo60/CoverflowAltTab#176]
Hello,

I would like to use "Coverflow AltTab" extension only for navigating among opened windows (`org.gnome.desktop.wm.keybindings switch-windows`, alt+tab on my setup), not for navigating among running softwares (`org.gnome.settings-daemon.plugins.media-keys switch-applications`, super+tab on my setup). It is related to ergonomics :
* IMO, Coverflow view is super efficient when you need to see the window content, but not when you just want to go from one software to another.
* My old eyes would be better catching when I'm using between-windows or between-applications switcher if the two views were highly different. 

On GNOME 43 (Ubuntu 22.04 LTS), with default settings, the extension activates Coverflow view for both between-windows and between-applications switcher. I didn't find any extension setting related to that behaviour. Is it intentional ?

1. If so, would it be possible to consider creating an option to alter between-windows view only ?
2. If not, here's a bug report.

Thank you !

**Comment by dsheeler** [comment]
@kirmaha Thank you for opening this issue. I'm not sure I understand what you're asking. Is it that you want super+tab to not activate coverflow at all?

**Comment by kirmaha** [comment]
@dsheeler Thank you for your answer. Yes, exactly ! I would like to activate Coverflow for alt+tab only.
I'm sorry I explained it in a super convoluted way.

**Comment by dsheeler** [comment]
@kirmaha, I apologize. I was not super clear on how the keybindings worked, so I didn't quite get your initial explanation, but I do now! I could make an option for this. Thank you for reporting this issue!

**Comment by dsheeler** [comment]
@kirmaha, could you try this commit: 09e7ddff39d0683b51b63ab95525a9e58897c44b? I have options to enable/disable switch-windows and switch-applications keybindings, and they seem to work for me.

**Comment by kirmaha** [comment]
@dsheeler, I would like to but I'm close to zero dev knowledge :-/ I'm able to edit .po files and pull requests to update them, but I suppose what you're asking is more complex than that ?

**Comment by dsheeler** [comment]
@kirmaha, to try it is pretty simple. Do you usually use a development version or just the official releases? You could try on a fresh clone:

`% cd /tmp`  
`% git clone git@github.com:dmo60/CoverflowAltTab.git`
`% cd CoverflowAltTab`
`% git checkout 09e7ddff39d0683b51b63ab95525a9e58897c44b`
`% make`

Let me know if you have any problems!

**Comment by kirmaha** [comment]
I use the official releases (that I install throught the flatpak Extensions manager).

Thank your for your help ! The second line returned and error (`git@github.com: Permission denied (publickey).`), but the following works : `git clone https://github.com/dmo60/CoverflowAltTab.git`.

I'm stuck with the `make` command, which returns :

> $ make
> msgfmt --check --output-file=CoverflowAltTab@dmo60.de/locale/fr/LC_MESSAGES/coverflow.mo CoverflowAltTab@dmo60.de/locale/fr/LC_MESSAGES/coverflow.po
> make: msgfmt: Aucun fichier ou dossier de ce type
> make: *** [Makefile:48 : CoverflowAltTab@dmo60.de/locale/fr/LC_MESSAGES/coverflow.mo] Erreur 127
> 

In English, it means that no folder or file with "msgfmt" type has been found.

**Comment by dsheeler** [comment]
I think you'd need to install a `gettext` package on your system to get that command.

**Comment by kirmaha** [comment]
Indeed, after installing gettext, it works. Just had to figure out that you have to run the command `cp -r ...` and reboot. Easy indeed, thanks !
Aaaaand... yes, your two options to bind Coverflow to switch-windows and switch-applications do the job. Perfectly ! This is exactly what I was looking for, I'm super happy ! Thank you so much.
