### ISSUE TITLE
Ctrl+Alt+Tab shortcut not working

### ISSUE THREAD

**Issue by machitgarha** [dmo60/CoverflowAltTab#182]
There is a keyboard shortcut for switching to top bar in Gnome, which is Ctrl+Alt+Tab (see [here](https://help.gnome.org/users/gnome-help/stable/shell-keyboard-shortcuts.html.en)). When the extension is enabled, it stops working.

Other than me, who on earth would use that shortcut anyway? :)

**Comment by dsheeler** [comment]
Is this a new thing? Or do you know when it started?

**Comment by machitgarha** [comment]
I started using the shortcut just today with the extension, but I'm not sure if it is new or not.

**Comment by dsheeler** [comment]
@machitgarha, do you have any idea why coverflow would bind to that shortcut? Doesn't seem like the right thing to do, but it does it right now.

**Comment by machitgarha** [comment]
@dsheeler, made the change. It's a surprise for me nobody created an issue for the last ten years.
