### ISSUE TITLE
[Bug] Gnome freezes completely, have to reboot

### ISSUE THREAD

**Issue by postsolar** [dmo60/CoverflowAltTab#183]
Not sure if the extension is to blame or it's something else, but it happens when I'm continuously switching between windows with alt/win+tab/` multiple times. Started just today and my extensions update automatically so can't tell on which version it started. I'm on Ubuntu 22.10, please tell me which logs and info to add. Thanks.

**Comment by machitgarha** [comment]
Have you tried disabling all other extensions before testing?

**Comment by postsolar** [comment]
> Have you tried disabling all other extensions before testing?

Hello, sorry for late reply. No matter how hard I try I can't replicate this anymore, so I will mark this as closed now.
