### ISSUE TITLE
Cleaning repository files up

### ISSUE THREAD

**Issue by machitgarha** [dmo60/CoverflowAltTab#186]
The repository has duplicate/extra files, which should be removed. I wanted to clean stuff up, but am creating an issue before to make sure it will be accepted in the case of a PR.

The changes would be merging `CoverflowAltTab@*` directories contests into the root directory (and merging `metadata.json`) and removing those directories, and updating `buildforupload.sh` and `Makefile` files where they reference the directories.

**Comment by dsheeler** [comment]
We should make those changes, yes.
