### ISSUE TITLE
Cannot switch windows between the same application

### ISSUE THREAD

**Issue by lomirus** [dmo60/CoverflowAltTab#192]
I opened 2 windows of firefox: one is regular window, and another is private window.

When press super key, it is like below, showing both windows:

![Screenshot from 2023-02-03 17-13-53](https://user-images.githubusercontent.com/21173956/216560517-a84b477c-7fbc-4fa4-ba08-52bd43a987d7.png)

However, when I tried to press alt+tab to switch window, it doesn't work. So I kept pressing it to see what happened, and then found that there was only one window available:

![Screenshot from 2023-02-03 17-12-45](https://user-images.githubusercontent.com/21173956/216559744-c52b7af6-66bc-4afc-82ad-afc528a1e9b9.png)

**Comment by sergiotca** [comment]
Same issue, and it started recently.

Using Manajaro & Gnome 43.2 under X11
Extension V58

**Comment by dsheeler** [comment]
Thanks for the reports! I can reproduce this, so I should be able to fix.

**Comment by careca1970** [comment]
Seems like it is same issue I noticed.

If you have many “applications” and some “windows” of same application,
switching between “applications” (Alt-Tab) works, but once you try to switch “windows of same application” (Alt-^) it does not reflect same behavior of “Gnome standard switcher”.
With actual behavior, one must first switch the “application group” (Alt-Tab), release Alt key, and then use “Alt-^” to choose between windows.

To resume, switching between “windows” should be possible during “application” switching (without releasing Alt-key), just swapping “Tab” by “^” keys.

By the way, MANY THANKS for very nice and functional extension !

**Comment by dsheeler** [comment]
9870b8a21c635014b9e72c3c8c7fc9f0dde0bbef Should fix this!

**Comment by lomirus** [comment]
@dsheeler There are still some problems. In the old version that still works, for example, there are three windows: A1, A2 and B1. A1 & A2 are the same application but different windows. When you focus A1 and then A2, and then you press the `alt` + `tab`, it will switch back to the A1 (the last window that you focused). However in the new version, it can only switch between the Ax and B1, despite the focusing order. It's very inconvenient when you just want to switch between two browser windows but there is also a terminal window, so you can only switch to the terminal window.

**Comment by lomirus** [comment]
My keyboard shortcut settings are:

- Switch Application: Super + Tab
- Switch Windows: Disabled

I don't know why "Switch Windows" is disabled (maybe because of the gnome upgrade), but it is fixed now by the solution in #190.
