### ISSUE TITLE
No way to disable the application sub-switcher?

### ISSUE THREAD

**Issue by pablo-fernandezz** [dmo60/CoverflowAltTab#193]
I would like to disable the sub-switcher that pops up when you have more than one window of the same application opened. I have searched online, looked into the extension settings, and even used dconf editor to see if there was an option to disable it.
Maybe I’m missing something?
The screenshot is just for showing what I mean with application sub-switcher, as I don't know if that is it's official name.

![Captura desde 2023-02-16 18-29-59](https://user-images.githubusercontent.com/68915352/219443918-413e3f33-bf91-4c47-bc8a-9cbff59f2ea9.png)

**Comment by dsheeler** [comment]
@pablo-fernandezz, thank you for your question! can you check out #190 and let me if that discussion (especially the keybinding settings at the end) helps?  With the correct keybindings, you can avoid seeing the application sub-switcher. I'm still kind of figuring out the sub-switcher stuff and really appreciate feedback!

**Comment by pablo-fernandezz** [comment]
Thanks a lot! It helped and now it is disabled. 
I simply overlooked the issue you mentioned. Also thanks for the quick response. 
Greetings
