### ISSUE TITLE
iter over all windows

### ISSUE THREAD

**Issue by rudrab** [dmo60/CoverflowAltTab#199]
Previously the app was itering over all open windows. After the current update, with alt-tab, its itering over the apps. What I mean is if I have 2 terminal window open, I cant see both with alt+tab. I have to alt+tab to a terminal then freshly do alt+`. 

Can I change this behaviour?

**Comment by dsheeler** [comment]
Yes. Check out #190.

**Comment by rudrab** [comment]
DOne. Thanks a lot. The problem was in gnome setting switch application was disabled

**Comment by dsheeler** [comment]
You are very welcome!
