### ISSUE TITLE
Switcher is not shown on wayland, gnome 43.5, fedora 37

### ISSUE THREAD

**Issue by danieldemus** [dmo60/CoverflowAltTab#205]
Neither keyboard shortcut produces any reaction. Switching still seems to happen in the background, but without any observable UI.
Everything works on x11 gnome.
It worked until recently where I assume wayland was update or wayland-x11 was updated.

**Comment by dsheeler** [comment]
Hi @danieldemus, thanks for the report! I just released a new version in the past few hours, did you upgrade to that version? It might fix your issue.

**Comment by danieldemus** [comment]
Hi. Which version number should be in the manifest?

When I look at https://extensions.gnome.org/extension/97/coverflow-alt-tab/ the highest version in the dropdown for 43 is 61, even though I apparently have 64 installed, which is nowhere to be found.
There is a 65 for gnome 44.

**Comment by danieldemus** [comment]
> Hi @danieldemus, thanks for the report! I just released a new version in the past few hours, did you upgrade to that version? It might fix your issue.

Hi. Which version number should be in the manifest?

~~When I look at https://extensions.gnome.org/extension/97/coverflow-alt-tab/ the highest version in the dropdown for 43 is 61, even though I apparently have 64 installed, which is nowhere to be found.
There is a 65 for gnome 44.~~

OK, so when I reinstalled it to 61 it works. Sorry to bother you.

**Comment by dsheeler** [comment]
@danieldemus sorry for being confusing!  You got it the right version for 43.  The new version didn't actually fix anything, but the issue you're seeing under wayland and 43 is fixed by gnome 44.
