### ISSUE TITLE
CoverflowAltTab Ignores Certain Gnome Native Apps: Nautilus and Gedit

### ISSUE THREAD

**Issue by TheRoarkster** [dmo60/CoverflowAltTab#206]
I'm hoping this is not just me, but when I use`CoverflowAltTab` to Alt-Tab between applications, it ignores _certain_ Gnome native apps, specifically `Nautilus` and `Gedit`.  

So if I, say, switch from `Nautilus` to `Firefox` by pressing Alt-Tab, and then try to switch back to `Nautilus` by pressing Alt-Tab again, `CoverflowAltTab` will note select `Nautilus`, but rather the last non-Gedit/Nautilus app used.

Note that this issues _does not_ occur when switching between other Gnome native apps like `Gnome-Disks`, `Gnome Calculator`, and `Gnome-Terminal`.  

Here is info about my system:
```
System:
  Host: manjaro-yoga Kernel: 5.15.114-2-MANJARO arch: x86_64 bits: 64
    Desktop: GNOME v: 44.1 Distro: Manjaro Linux
```

**Comment by dsheeler** [comment]
Thanks for the report! A few questions:

Are you using wayland or X11?

What version of Coverflow are you using?
 
Could you do a screencast?

**Comment by TheRoarkster** [comment]
Thanks @dsheeler. Will get the screencast soon.  But here is the other info:

X11
Coverflow v.65

**Comment by TheRoarkster** [comment]
I'm going to close this.  A recent update has remedied it; perhaps it was a `gnome-shell` issue.
