### ISSUE TITLE
Gnome 45 Support?

### ISSUE THREAD

**Issue by nater1983** [dmo60/CoverflowAltTab#208]
I am wondering due to Gnome 45 switching to ESM will there be a new release supporting Gnome 45???

**Comment by rudrab** [comment]
I am getting error:
The settings of extension CoverflowAltTab@palatis.blogspot.com had an error:
```
SyntaxError: export declarations may only appear at top level of a module
```

Stack trace:
```
@file:///home/rudra/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/prefs.js:28:16
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```
when installing it in f39.

**Comment by rudrab** [comment]
The possible error is: https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by dsheeler** [comment]
Yes, there will be a new release for 45. Yes, @rudrab, I don't know all the issues but I anticipated import problems.

**Comment by DarkXero-dev** [comment]
Gnome 45 is out on Arch hoping to see update soon. Thanks for the hard work

**Comment by rudrab** [comment]
branch 208 is working properly on gnome 45 (fedora 39)

**Comment by mlmilliman** [comment]
Freezes on activation for Ubuntu 23.10 with Gnome 45. More investigation necessary.

**Comment by dsheeler** [comment]
@mlmilliman you are using the 208 branch? So you hit alt-tab and does anything come up? Whole gnome-shell freezes up?

**Comment by nater1983** [comment]
branch 208 is working properly on gnome 45 (Slackware 15.1 (Current) )

**Comment by mlmilliman** [comment]
> @mlmilliman you are using the 208 branch? So you hit alt-tab and does anything come up? Whole gnome-shell freezes up?

Yes I am using branch 208. I downloaded it, built it, and installed it into a clean directory. I checked the metadata.json file to confirm I'm using the correct version too. Not only does GNOME freeze up but also Ubuntu to the point I have to do a hard reset on the computer. I cannot escape or start a new session or even kill GDM3. I didn't expect that hard of a failure. I'll see if I can replicate it and look through the log files to see where it is crashing.

**Comment by Batwam** [comment]
I just tried branch 208 and worked fine for me. I've had issued restarting gnome-shell on X11 since testing 23.10 as it tends to crash rather than restart but this doesn't seem to be coverflowAltTab specific as I had the same issue testing updating other extensions.

**Comment by dsheeler** [comment]
> > @mlmilliman you are using the 208 branch? So you hit alt-tab and does anything come up? Whole gnome-shell freezes up?
> 
> Yes I am using branch 208. I downloaded it, built it, and installed it into a clean directory. I checked the metadata.json file to confirm I'm using the correct version too. Not only does GNOME freeze up but also Ubuntu to the point I have to do a hard reset on the computer. I cannot escape or start a new session or even kill GDM3. I didn't expect that hard of a failure. I'll see if I can replicate it and look through the log files to see where it is crashing.

Great! If you can replicate that'll be super helpful. Thank you!

**Comment by dsheeler** [comment]
Oh, and I also have x11 crashing on restart. I used that feature extensively to develop extensions, but since it's broken, I switched to wayland!

**Comment by Batwam** [comment]
Same here. Turns out it's a know issue but as long as you close all apps before restarting it works: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7050

**Comment by DarkXero-dev** [comment]
I think what's going on is related to this mutter issue
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7050

**Comment by dsheeler** [comment]
Hey guys: I submitted the 208 branch plus new swipe functionality to the extensions web site for approval. Hope it's up soon!

**Comment by dsheeler** [comment]
@DarkXero-dev and @Batwam: Is there a way to restart the shell that doesn't cause a crash?

**Comment by Batwam** [comment]
the only solution I found so far is to close all windows before restarting. if you miss one, it will crash which is kind of annoying as it means that you can leave the apps you were testing open... but still better than having to close/reopen the session. 

personally, I made a script called `re` which includes the following so, instead of doing Alt+F2+`r`, I'm now doing Alt+F2+`re` and the script runs `wmctrl -l | wc -l` to make sure no window is left open before restarting the shell. The script also reopens whatever app I'm testing with (reopens the IDE, ...) so I don't have to do it myself. I haven't found a better solution yet and you can't even restart automatically from your install script as the terminal/IDE itself needs to be closed :-(

```
num_windows=$(wmctrl -l | wc -l)
if [ "$num_windows" -gt 0 ]; then
	if [ -t 0 ]; then #check if run from terminal or GUI
		echo -e "\e[31mPlease close all apps before restarting Gnome\e[0m"
	else
		zenity --warning --text "Please close all apps before restarting Gnome"
	fi
fi
```

**Comment by dsheeler** [comment]
Thanks for the info! I want this problem fixed ASAP!

**Comment by DarkXero-dev** [comment]
> Thanks for the info! I want this problem fixed ASAP!

So does everyone else. It's a Mutter issue so please add your voice by nagging to them

**Comment by dsheeler** [comment]
I just applied their fixes on a fedora 39 running in boxes.  It works! I think they don't understand why the fix works...

**Comment by dsheeler** [comment]
I just installed the fix to /usr/local on my running system.  It works. Wow. Like the good old days!

**Comment by dsheeler** [comment]
If anyone wants the patch for mutter: 
[patch.txt](https://github.com/dmo60/CoverflowAltTab/files/13062016/patch.txt)

**Comment by nater1983** [comment]
My i ask what the patch fixes in mutter @dsheeler ....

**Comment by dsheeler** [comment]
@nater1983: The patch generally allows you to restart X11 sessions without a crash. 

I can't tell you the first thing about the mutter internals, just I tracked down a few edits described in this post: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2445#note_1747876 and reverting this commit here https://gitlab.gnome.org/GNOME/mutter/-/commit/15b25568b29ec0e082f6a18fef550078102aaca1?merge_request_iid=2445. I started with the link above provided by @Batwam (thank you very much, @Batwam!) in this post: https://github.com/dmo60/CoverflowAltTab/issues/208#issuecomment-1762632316

**Comment by nater1983** [comment]
Thats what I thought it was , I kinda followed the thread abit. I have applied this patch to Gnome 45 for Slackware thank you so much.

**Comment by dsheeler** [comment]
I couldn't believe how simple the edits turned out to be: remove this line, add this line, done. And then restart worked. I like little miracles :).

**Comment by nater1983** [comment]
Well in future releases Gnome says they will be removing X11 code in favor of Wayland but I think since I am maintaining Gnome for Slackware with a group of devs we will just patch the X11 code back into Gnome.

**Comment by dsheeler** [comment]
Cool!

Wayland is the future, but X11 restart is really important for me to develop this extension in particular.  I can't really develop this extension with nested wayland since the outer shell captures the Alt-Tab (there must be a way to make that happen, but I don't know how).

This X11 restart crash has at least got me started looking at virtual machines. But even there I have to login/logout instead of restarting. They are really getting pretty good with wayland functionality all being there. But this restart thing keeps me interested in X11

**Comment by Batwam** [comment]
yeah, restart capability is the only reason I'm still using X11 as it's a must when working on extensions...

**Comment by nater1983** [comment]
> Cool!
> 
> Wayland is the future, but X11 restart is really important for me to develop this extension in particular. I can't really develop this extension with nested wayland since the outer shell captures the Alt-Tab (there must be a way to make that happen, but I don't know how).
> 
> This X11 restart crash has at least got me started looking at virtual machines. But even there I have to login/logout instead of restarting. They are really getting pretty good with wayland functionality all being there. But this restart thing keeps me interested in X11

I agree X11 has been around for so long ( for me I prefer X11 over Wayland ) but you are right sooner or later Wayland would need to have the whole restart Gnome Shell feature ( hopefully ) added.

**Comment by dsheeler** [comment]
I used to sometimes use X11 over a fast network logged in to a different computer :). Wayland will never do that. But it probably shouldn't... I don't know :).

**Comment by nater1983** [comment]
Same only time will tell

**Comment by Batwam** [comment]
I'll mention your patch on gitlab in case it can help getting this fixed upstream. I hope that's ok.

**Comment by dsheeler** [comment]
I think my patch works, but not sure it's really correct, and I got it from their work, so I'm not sure it'll be useful, but a push never hurts :)

**Comment by mlmilliman** [comment]
I did a clean build and install of this branch and it still crashes Ubuntu 23.10. The extension is activated but fails to bring up CoverFlow. The mouse still moves abut I cannot exit out of the extension nor open a new tty. I have to do a cold boot to recover. I could try to ssh into the machine to see if the kernel is still running and it is just a gdm3 freeze.

**Comment by dsheeler** [comment]
@mlmilliman, I suspect somehow the coverflow extension is crashing while still modal (all keyboard events go only to it). That would explain not being able to get a tty. I suspect you'd be able to ssh in, but let's find the bug. Can you capture the output of 

`$ journalctl -f /usr/bin/gnome-shell`

before and during the crash? I.e., start capturing that command and make the crash happen?

**Comment by dsheeler** [comment]
@mlmilliman, I tried installing ubuntu on boxes, but it was freezing up on me and unusable.  Not sure why, so I couldn't reproduce the bug.

**Comment by molitona** [comment]
hello @dsheeler 
is cloning the repo to ~/.local/share/gnome-shell/extensions will get the extension work ?
I use arch on x11 and i can help reporting any issues..

**Comment by Batwam** [comment]
@molitona no, it won't. You need to either install the version from extensions.gnome.org or clone the report in your git folder and run `make all`
https://github.com/dmo60/CoverflowAltTab#gnome-shell
