### ISSUE TITLE
Locked on looping windows

### ISSUE THREAD

**Issue by allanforever** [dmo60/CoverflowAltTab#24]
When I change the dim-factor option and hit Alt+Tab my screen stay locked on the looping window, and i can select text on my terminal behind the config window (see pictures
![captura de tela de 2014-02-12 17 32 32](https://f.cloud.github.com/assets/6664994/2160373/392b2b08-94b7-11e3-9eb4-d51cc24af0e1.png)
![captura de tela de 2014-02-12 17 33 01](https://f.cloud.github.com/assets/6664994/2160374/392bb8fc-94b7-11e3-9c81-ae4d6a7504f8.png)

When I was trying to repeat the bug something different happen: I could access the Coverflow with Alt+Tab, the windows changed, but whatever application i tried to access gives me a blank terminal that was on my workspace, but it was locked (couldn't select or type any text)
)

**Comment by p91paul** [comment]
> Ok thanks for reporting. I will try to reproduce it by myself if I have some spare time (and I'm actually hoping to have a bit of spare time starting from March, so maybe this isn't a void pledge).

My pledge was so void!
Right now I think that particular setting is applied only after a Gnome restart. So I guess it's not reproducible anymore.
