### ISSUE TITLE
Compatibility issue with another extension

### ISSUE THREAD

**Issue by opeterson** [dmo60/CoverflowAltTab#25]
Hello!

I've recently run into problems with this extension. I've found that when I have the Optistatus extension turned on, your extension no longer works at all, and the native alt-tab functionality is also disabled. Naturally I just leave Optistatus off to solve this, but I thought you might be interested. Please let me know if there's anything I can do to help, should you decide to investigate. Other than that little hiccup, it works great for me!

The Optistatus extension can be found here: https://extensions.gnome.org/extension/710/optistatus/

**Comment by lkc0987** [comment]
I ran into this the other day (Ubuntu 18.10 + Gnome 3.30.1) and made a small change to the code. (basically added a conditional check to see if get_meta_windowis a function)

`for (let i in windowActors)`
`   if (typeof windowActors[i].get_meta_window === 'function')`
`       windows.push(windowActors[i].get_meta_window());`

**Comment by p91paul** [comment]
Thanks for your patch! Could you try installing from master to test the fix?

**Comment by lkc0987** [comment]
verified works - master branch.
