### ISSUE TITLE
Update on GNOME extensions site

### ISSUE THREAD

**Issue by DreaminginCodeZH** [dmo60/CoverflowAltTab#30]
First of all, thank you for your great work, and I have always loved this extension. Sadly it stopped to work after the upgrade to GNOME 3.14.

But since the 3.14 compatability issue has been fixed by #29 , can you push an update to https://extensions.gnome.org/extension/97/coverflow-alt-tab/ ? So that users can get an update from the official site.

**Comment by wilfm** [comment]
+∞

**Comment by dmo60** [comment]
I've uploaded a new release with support up to 3.16. It is currently in review, so should be available within a few days. Sorry for letting you down so long, but I had other priorities recently (and still have)...
