### ISSUE TITLE
add option to include windows on all workspaces

### ISSUE THREAD

**Issue by psykotik1** [dmo60/CoverflowAltTab#35]

**Comment by andreicristianpetcu** [comment]
Please add this feature! :D

**Comment by p91paul** [comment]
duplicates #13

**Comment by andreicristianpetcu** [comment]
Thank you @p91paul.

**Comment by andreicristianpetcu** [comment]
Hmmm I cannot close this issue. Please close it since it is a duplicate.

**Comment by p91paul** [comment]
only @psykotik1 (reporter) or @dmo60 (owner) can do that!
