### ISSUE TITLE
Extension does not work, error on Extension loading

### ISSUE THREAD

**Issue by Kruno313** [dmo60/CoverflowAltTab#36]
Hi
I have an permanent problem on Linux Mint 17.1 cinnamon 64Bit. The Extension does not work and I have an error message on start, something like "Cinnamon has problem starting extension..".
The "Looking Glass" shows an error:
"error t=2015-04-27T20:14:50Z [Extension "CoverflowAltTab@dmo60.de"]: Extension is not compatible with current Cinnamon version
error t=2015-04-27T20:14:50Z Could not load extension CoverflowAltTab@dmo60.de".

I have manualy installed it into  ~/.local/share/gnome-shell/extensions/.

**Comment by p91paul** [comment]
This issue is quite old, sorry for the lack of support. Do you still have the problem?

**Comment by Kruno313** [comment]
Hi
I have not used it since then, but installed again today on my Mint with cinnamon and it seams to work now. On activation, cinnamon said that the extension is not compatible with my cinnamon release, but I ignored it and it worked.
Thanks
