### ISSUE TITLE
coverflow stopped working after reboot/shutdown

### ISSUE THREAD

**Issue by k0377** [dmo60/CoverflowAltTab#37]
I've to disable and re-enable the extension in `gnome-tweak-tool` after every reboot or shutdown. Then coverflow will work again. If I do not, I get the default look of `alt+tab`.

**Comment by k0377** [comment]
Installed/enabled extensions:
- alternate tab
- applications menu
- coverflow alt-tab
- dash to dock
- drop down terminal
- media player indicator
- open weather
- rss feed
- window overlay icons

**Comment by k0377** [comment]
Hmm, seems to work now but idk why. :joy_cat:

**Comment by k0377** [comment]
ok, ive to reopen this, really strange issue.

**Comment by p91paul** [comment]
You have alternate tab and coverflow alt-tab installed together, and they conflict (they are both alt-tab replacements). Depending on the last one gnome-shell decides to activate, you'll get one or the other.

If you want coverflow, disable alternate and vice-versa.

**Comment by k0377** [comment]
You're right, I disabled now alternate tab and coverflow works all the time now! :heart_eyes_cat:
