### ISSUE TITLE
Extension doesn't load at login on Gnome 3.14

### ISSUE THREAD

**Issue by alexluecke** [dmo60/CoverflowAltTab#42]
Extension is not loaded on start up or when Gnome Shell is restarted. Works fine otherwise.

Debian 8
GNOME Shell 3.14.4

**Comment by alexluecke** [comment]
After looking at the extension and googling a little, this is almost certainly a gnome problem, not Coverflow. https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1236749

**Comment by alexluecke** [comment]
It was the former so that's probably not the same issue.

**Comment by p91paul** [comment]
do you happen to have installed and enabled some other alt-tab modifier, like alternate alt-tab? debian installs it by default AFAIK. If this is the case, you need to disable the other alt-tab extension because it overrides coverflow modifications.

**Comment by alexluecke** [comment]
Wow good call. I found 'Alternatetab' in my extensions list and disabled it. Works flawlessly.

**Comment by p91paul** [comment]
Yeah, I cheated :) you're not the first one ;) https://github.com/dmo60/CoverflowAltTab/issues/37
