### ISSUE TITLE
[ WISH ] Show windows from all workspaces

### ISSUE THREAD

**Issue by cig0** [dmo60/CoverflowAltTab#49]
Thanks for considering this.

**Comment by p91paul** [comment]
This was proposed in pull requests #21 and #48. Me and @dm60 didn't like very much the behavior #21 obtained, but I haven't looked at #48 code yet. Can you try one or both proposals and share your thoughts about them? (i.e. does the implementation satisfy your needs?)

**Comment by joncamfield** [comment]
I love the current options, but would like the ability to use different hot-key combos to access them (e..g Alt+Tab for current workspace windows, Win+Tab for all workspaces, Alt+Win+Tab for all, current first, but obviously should be user-configurable).

**Comment by p91paul** [comment]
This was solved in #58. @joncamfield you are right, you are requesting #13; in the meantime, look at https://github.com/dmo60/CoverflowAltTab#customization to change keybindings through system settings.
