### ISSUE TITLE
Stops working after reboot

### ISSUE THREAD

**Issue by asdf23** [dmo60/CoverflowAltTab#52]
The extension works great until i reboot. Then if I visit extensions.gnome it appears to be on but it behaves as off. If I toggle the switch it works again. I did not add a permenate trust to this website nor do I have a online gnome account (not sure if that is related).

**Comment by p91paul** [comment]
Sounds like you have another alt-tab replacement extension installed and enabled; some distributions ship with AlternateTab installed by default, which conflicts with CoverflowAltTab, and when enabled triggers the behavior you are describing. Please check your installed extension list at https://extensions.gnome.org/local/ and disable the offending ones!

**Comment by asdf23** [comment]
That was the problem, thank you
