### ISSUE TITLE
having to enable the extension again and again once start

### ISSUE THREAD

**Issue by ljhui** [dmo60/CoverflowAltTab#63]
This is a good extension,but unluckily it works not well on my laptop Thinkpad T460p,my system is Fedora  24, the latest version.first I find this extension in  [extensions.gnome.org](https://extensions.gnome.org/extension/97/coverflow-alt-tab/), but it cannot be installed,while other extension can , so I have to install manually and enable it , but every time  I login in my laptop, it doesn't work , I have to enable it again , unlike other extension I have installed, how can I fix it?

**Comment by p91paul** [comment]
Most likely you have a conflicting extension, like Alternate Alt-Tab. Please check the README (i.e. the extension homepage). At the bottom there is a troubleshooting section!

**Comment by ljhui** [comment]
sorry ,I doesn't notice that. now  it's OK for me ,thanks!

**Comment by p91paul** [comment]
Good!Glad to be helpful!
