### ISSUE TITLE
Extension doesn't persist after logout

### ISSUE THREAD

**Issue by jorenheit** [dmo60/CoverflowAltTab#64]
When I log out of and back in to gnome 3, the extension is still enabled (set to "on") but the behavior has reset to the default Alt-Tab. I have to re-enable the extension to get it working again.

**Comment by p91paul** [comment]
You probably have Alternate Alt-Tab or some other conflicting extension installed. Please check the Troubleshooting section of the [repository homepage](https://github.com/dmo60/CoverflowAltTab#troubleshooting)!
