### ISSUE TITLE
3.21/3.22 non-fatal error

### ISSUE THREAD

**Issue by lachlan-00** [dmo60/CoverflowAltTab#66]
looks like something has changed in the 3.22 dev cycle. 

I get this error:
second argument to Lang.bind() must be a function, not undefined

The plugin still functions but displays an error in extensions.gnome.org, lg and tweak tool.
I don't know if there's a way to get the specific line that causes this error.

**Comment by p91paul** [comment]
Looks like the error happens while disabling the extension. I should have fixed it it the master branch, please test it out!

**Comment by lachlan-00** [comment]
I'm away from a pc till next week but I'll let you know asap

**Comment by p91paul** [comment]
Closing old issue.
