### ISSUE TITLE
Allow Alt+F4 to close selected app

### ISSUE THREAD

**Issue by gevera** [dmo60/CoverflowAltTab#67]
in Openbox and macOS its possible to close current selected app in Alt+Tab by Alt+F4. Please, add this feature. Thank you

**Comment by p91paul** [comment]
In Coverflow Alt-Tab that is possible by pressing q while keeping alt down. I will investigate if adding F4 causes some issues!

**Comment by p91paul** [comment]
Feature added and released to extensions.gnome.org (it'll take some days to be accepted though)
