### ISSUE TITLE
animate wait time

### ISSUE THREAD

**Issue by biji** [dmo60/CoverflowAltTab#68]
Please add option to not animate at all, when we alt tab quickly (for example: animate wait time: 1s)

thanks

**Comment by p91paul** [comment]
I very much think there is already; the animation appears only if you keep alt pressed for more than 150ms (which is long enough I think, a quick alt-tab is way faster). Which gnome-shell/cinnamon version are you on?

**Comment by biji** [comment]
well 150ms is just too fast for my hand :D 
i'm using 3.22 (fedora 25)

thanks

**Comment by DreaminginCodeZH** [comment]
Don't think 150ms is short for a single key combo - making it too ling will render the switching lagging.

**Comment by doncullen** [comment]
Need to keep in mind that there's people who don't have ability to maneuver their hands quickly, such as the disabled, the elderly, and so on.  While I don't have this experience, I can definitely see the need for an option to be provided so users can tweak it to their preference.

**Comment by p91paul** [comment]
From what I can see, the current behavior loads the animation when the first switch is actually completed.
The 150ms limit was put there to avoid showing half animations when switching was very fast.
If you see the animation, it means you kept pressed the keys long enough for the animation to show properly, so there is no need to prevent the animation from showing.
While I'm still going to accept pull request making the initial delay configurable (currently is a constant INITIAL_DELAY_TIMEOUT in switcher.js), for now I'm going to close this issue.

Point is, disabled/elderly/anyone else is not really prevented from using this extension, being fast is not _required_. They'll just see, however briefly, a fully formed animation which is not really slowing them down.
