### ISSUE TITLE
(some) fullscreen windows in gnome-shell and wayland do not work as expected.

### ISSUE THREAD

**Issue by ghost** [dmo60/CoverflowAltTab#70]
some fullscreen windows do not get placed correctly in wayland after alt+tab in and out.

1. Start gnome on wayland.
2. Start xonotic-sdl (just as an example)
3. On the main menu press alt+tab to tab out...
4. Press alt+tab again to tab in
See that the window is misplaced.

if you now:
1. press windows key...
2. select a different window
3. press windows key again
4. select xonotic window
window switching works just fine.

**Comment by machitgarha** [comment]
On Gnome 3.36, it is unreproducable. Maybe the bug is fixed across the recent changes, and we should close this issue?

**Comment by p91paul** [comment]
Closing as suggested.
