### ISSUE TITLE
Doesn't work on fedora 26 / Gnome 3.24

### ISSUE THREAD

**Issue by aryasenna** [dmo60/CoverflowAltTab#73]
It was working fine on Fedora 24/Gnome 3.22, how do I debug this?
Reloading the extension and restarting Gnome shell doesn't have any effect. Only default alt-tab is shown.

**Comment by p91paul** [comment]
This is quite strange, I'm using this extension on gs 3.24 on Arch Linux. Do you possibly have other extensions installed, perhaps Alternate Alt-Tab which sometimes gets installed by distributions?

If this is not the case, please collect the output from `journalctl -f` while you enable/disable the extension. Did you install from e.g.o or manually from this repository?

**Comment by aryasenna** [comment]
Uh, so I booted my Fedora install intending to get journalctl, and the extensions now works.😅

Closing the issue as I can't reproduce it. Thanks Paul for chiming in.
