### ISSUE TITLE
CentOS7.5 can't work with this CoverflowAltTab

### ISSUE THREAD

**Issue by liangjiongyao** [dmo60/CoverflowAltTab#81]
i have already installed it on the https://extensions.gnome.org/extension/97/coverflow-alt-tab/ ,also restarted gnome-shell,but when i press Alt+Tab,nothing happen

**Comment by p91paul** [comment]
It should work. Do you see any errors in journalctl? Did you try manual install as described in https://github.com/dmo60/CoverflowAltTab#installation?

**Comment by liangjiongyao** [comment]
![2018-06-06_09-28](https://user-images.githubusercontent.com/30697104/41010765-17c17736-696c-11e8-93c7-df1a44f97332.png)
[root@localhost ~]# ls /root/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/
config.js             keybinder.js  metadata.json  settings-schema.json
CoverflowAltTab.pot   lib.js        platform.js    switcher.js
coverflowSwitcher.js  locale        prefs.js       timelineSwitcher.js
extension.js          manager.js    schemas
[root@localhost ~]# 

i exactly installed CoverflowAltTab according to this https://github.com/dmo60/CoverflowAltTab#installation? and there is no error in journalctl

**Comment by liangjiongyao** [comment]
![2018-06-08_09-20](https://user-images.githubusercontent.com/30697104/41134295-4076871e-6afe-11e8-9867-51fc116d14dc.png)

**Comment by p91paul** [comment]
Sorry but I still have no clue, good ol' "it works on my machine" applies here.

Please try this:
Disable all extensions (switching them off through the preference page in your screenshot should be enough)
Start journalctl -f
Restart gnome shell
Post the journalctl output

I know you already said the logs don't have errors, but let's try anyway...

**Comment by liangjiongyao** [comment]
it works,nothing need to do,just press ALT first then press TAB,i used to  press them at the smae time.

**Comment by p91paul** [comment]
Ok good then! Have a good time alt-tabbing!
