### ISSUE TITLE
But for Gnome-Shell 3.28.2????

### ISSUE THREAD

**Issue by xzj8b3** [dmo60/CoverflowAltTab#83]
But for Gnome-Shell 3.28.2???? It is one of the most comfortable extensions, but because it is updated so little????

**Comment by p91paul** [comment]
The extension works for me on 3.28. Now I've also pushed an update on extensions.gnome.org.
Thanks for bug report!

Why it is updated so little? Because my daily job is taking all my time and energy. Does someone want to step up and help me?
