### ISSUE TITLE
Icon/Text overlapping on HighDPI

### ISSUE THREAD

**Issue by fabiscafe** [dmo60/CoverflowAltTab#84]
When I choose the HighDPI mode of gnome (On wayland, not tested with X11) the icon overlapps the text in the bottom of the coverflow animation. This dont happens on "normal DPI mode"
![bildschirmfoto-20180811003004-3840x2160](https://user-images.githubusercontent.com/18744080/43984070-7f4eebe8-9cfe-11e8-8165-c5f182630dfb.jpg)

**Comment by p91paul** [comment]
mmm...I don't have an HighDPI screen, I'll need help on this one!

**Comment by Tids** [comment]
I think its possible to trigger this by just enabling 200% Scaling in the gnome settings. Otherwise I'll help if you can tell me how to do so :)

**Comment by p91paul** [comment]
I finally committed a fix to master.
This is actually a workaround, setting a fixed width and height on the icon, that will not be scaled and get smaller, so that the positioning calculations work.
But this should actually be fixed with a layout and/or good css.
