### ISSUE TITLE
Not working on Gnome 3.30

### ISSUE THREAD

**Issue by leixet** [dmo60/CoverflowAltTab#86]
The extension stopped working. I have to disable it to recover alt+tab functionality.

It's compatible with Gnome 3.30 or that's my problem? Thanks.

**Comment by p91paul** [comment]
@demokritos and all on this thread: please try branch gnome-shell-3.30. It originates from pull request #85 with changes to make it backwards compatible with 3.28.

I don't have a 3.30 available yet, so I'm unable to test it properly. It likely worked when @demokritos proposed it, but I might have broken it with my changes.

**Comment by demokritos** [comment]
@p91paul, I tried gnome-shell-3.30 branch. It works well on gnome-shell 3.30. Thanks.

**Comment by leixet** [comment]
@p91paul Thanks! it worked!

**Comment by aronpc** [comment]
Thanks!

**Comment by johnnyg** [comment]
Can also confirm branch gnome-3.30 works fine on gnome 3.30 (which has been rolled out to Archlinux)

**Comment by psykotik1** [comment]
cant use timeline mode in gnome 3.30 arch linux

**Comment by p91paul** [comment]
@psykotik1 fixed in master.
@pablodav I wasn't aware animations can be disabled. However I think this extension shouldn't work with animation disabled!
