### ISSUE TITLE
Cannot detect Alt+Tab in Gnome 3.18

### ISSUE THREAD

**Issue by davidhu3141** [dmo60/CoverflowAltTab#91]
Nothing showed after pressing Alt+Tab in Gnome 3.18. I checked `/var/log/syslog` and found these two lines appeared after pressing Alt-Tab:

`Gjs-WARNING **: JS ERROR: TypeError: binding is null`
`Manager.prototype._startWindowSwitcher@/home/.../.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/manager.js:99`

It seems that a wrong `keybinder` object is used. The problem is solved after commenting out these lines in `extension.js`:

![2018-10-29 18-05-40](https://user-images.githubusercontent.com/5648920/47643555-c3278000-dba6-11e8-8040-1a5e46706dd5.png)

**Comment by p91paul** [comment]
Gnome shell versions older than 3.26 are now to be supported in branch gnome-shell-3.26. I've unrelased version 34 on extensions.gnome.org, which means that 3.28+ users will download the latest version while older will now download version 33 (the latest known working). Please uninstall and reinstall the extension from extensions.gnome.org!
