### ISSUE TITLE
Needs a new maintainer

### ISSUE THREAD

**Issue by p91paul** [dmo60/CoverflowAltTab#95]
Gnome 3.32 introduces breaking changes...again. I'm truly sorry, but I'm unable to properly maintain this extension now. If anyone wants to step up, please contact me. You can get my email from the commit history.

**Comment by kirbyfan64** [comment]
I might take a look at this while I'm trying to port some of the other extensions to use; this one doesn't even seem to really use Lang.Class, which makes it a lot easier.

**Comment by p91paul** [comment]
I'm on 3.32 and I don't see any issues, so it probably works...apparently this extension was one of the few spared by the 3.32 ES6 switch. Leaving this issue opened as the main problem (me lacking the time to be a proper maintainer) stands.

**Comment by dffischer** [comment]
I tested the extension under gnome-shell 3.32 on Arch Linux and propose a [pull request to declare compatibility](https://github.com/dmo60/CoverflowAltTab/pull/98).

**Comment by machitgarha** [comment]
@p91paul Only for the sake of knowledge: These kinds of BC breaks is going to be minimal in the next Gnome version (Gnome 40). See [this](https://www.phoronix.com/scan.php?page=news_item&px=GNOME-40-Better-Extensions).

**Comment by p91paul** [comment]
> @p91paul Only for the sake of knowledge: These kinds of BC breaks is going to be minimal in the next Gnome version (Gnome 40). See [this](https://www.phoronix.com/scan.php?page=news_item&px=GNOME-40-Better-Extensions).

I'd really like to believe that, but this was already promised many gnome versions ago. I just guess it's ok to improve on software, even if it means breaking stuff. I'll try to keep this extension alive for as long as I can, and I'm just glad I got a lot of help from the community over the years I've been doing this.

**Comment by machitgarha** [comment]
@p91paul Yes, I do agree with you on Gnome. I'm not really hopeful with the saying, too. However, on BC breaks, I don't agree. Keeping backward-compatibility is really important IMHO. Breaking stuff just takes too much time and effort. That's why I see in discussions almost every Gnome extension developer says "What the hell, Gnome? Another break?". I personally hate BC breaks, if they happen too much.

**Comment by p91paul** [comment]
Yeah, I'm in the extensions maintenance business since I re-uploaded this one to e.g.o. in late 2012, taking over from original developer Palatis. Since then I took over another 4 ones... and I can confirm "What the hell, Gnome? Another break?" is most certainly the gnome-shell extension maintainer mantra.

**Comment by p91paul** [comment]
I would still like for someone to step up in my place.
Maybe one day I will give up entirely, and someone will be forced to step up, like I was forced to a long time ago.
For now, I will keep maintaining hoping contributions continue to arrive like they do now.
