### ISSUE TITLE
Quickly scrubbing does not register all presses

### ISSUE THREAD

**Issue by WhiteHusky** [dmo60/CoverflowAltTab#96]
With the default Gnome app switcher I could quickly tab through all my applications as fast as my hand would let me, however Coverflow discards keypresses while it's animating to the next window.

It should keep track of presses and speed up the animation to catch up so 10 quick button presses will result in the 10th window regardless.

**Comment by p91paul** [comment]
I should have fixed this in master, will work in Gnome 40 only.
