### ISSUE TITLE
JS WARNING reference to undefined property "legacyTray"

### ISSUE THREAD

**Issue by PJSingh5000** [dmo60/CoverflowAltTab#97]
I see the following error in my logs:
`JS WARNING: [/usr/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js 530]: reference to undefined property "legacyTray"`

This error is accompanied by the message message:
`Ignoring excess values in shadow definition`

GNOME Shell 3.32.0
Ubuntu 19.04

**Comment by p91paul** [comment]
This should be fixed in latest master, I just published a new release to e.g.o.
I should probably also advertise 3.32 support as I see no issues right now.
